from linkedlist import LinkedList

print("*** casting linkedlists to python lists: ***")
ll = LinkedList(1, 4, 3, "book")
ll.append("Kite")
print(type(ll), ll)
l = ll.toList()
print(type(l), l)

print("*** prepend: ***")
ll.prepend(8)
print(ll)
ll_empty = LinkedList()
ll_empty.prepend(3.14)
print(ll_empty)

print("*** popFirst: ***")
ll = LinkedList(2,3)
print(ll)
while ll.head:
    print(ll.pop().value)
    print(ll)
    print("---")
print(ll.popFirst())
print(ll)

print("*** insert: ***")
ll = LinkedList("Happy", "to see", "you")
print(ll)
ll.insert(0, "I'm")
print(ll)
ll.insert(1, "very")
print(ll)
ll.insert(5, "healthy")
print(ll)

print("*** remove: ***")
print(ll.remove(5).value)
print(ll)
print(ll.remove(1).value)
print(ll)
print(ll.remove(0).value)
print(ll)
print(ll.remove(-1))
print(ll.remove(3))
