from linkedlist import LinkedList
print("*** various inputs in LinkedList constructor: ***")
print(LinkedList(2, 3, 4))
print(LinkedList(range(12)))
print(LinkedList(["gold", 'silver', "diamond"]))
print(LinkedList(2))

print("*** empty linkedlists: ***")
ll_none = LinkedList(None)
ll_empty = LinkedList()
ll_bracket = LinkedList([])
print("ll_bracket", ll_bracket)
print("ll_none", ll_none)
print("ll_empty", ll_empty)

print("*** Equality of empty linkedlists: ***")
print("ll_bracket == ll_none", ll_bracket == ll_none)
print("ll_bracket == ll_empty", ll_bracket == ll_empty)
print("ll_empty == ll_none", ll_empty == ll_none)
print("Whether LinkedList(None) == LinkedList([None])? ", LinkedList(None) == LinkedList([None]))
print(LinkedList([None]))
print("*** append(), pop(), __str__() and __eq__() methods for linkedlists: ***")
x = LinkedList()
x.append("first element")
print(x)
x = LinkedList([9, 4])
y = LinkedList(9, 4)
x.append("book")
y.append("cat")
print("x:", x)
print("y:", y)
x.append([11,3])
y.append(17)
while x.length > 0:
    print("x:", x)
    print("y:", y)
    print("Whether x == y? ", x == y)
    x.pop()
    y.pop()
    print("-----------------")

print("x:", x)
print("y:", y)
print("Whether x == y? ", x == y)
print("Whether x == a freshly created empty linkedlist? ", x == LinkedList())
