from queue import Queue


print("      *** Different versions of empty queue *** ")
q_empty = Queue()
q_none = Queue(None)
q_bracket = Queue([])
print(q_empty, q_none, q_bracket, "\nWhether qll_empty == qll_none? ", q_empty == q_none)
print("      *** from lists and range *** ")
q1 = Queue([2, 4, 6])
q2 = Queue(range(2, 8, 2))
print(q1 == q2)
print(q2)
print("      *** enqueue *** ")
q1 = Queue(1, 2, 3)
q1.enqueue(4)
print(q1.first.value)
print(q1.last.value)
print(q1)
q2 = Queue(1, 2, 3, 4)
print(q1 == q2)
print("      *** enqueue the first element *** ")
q1 = Queue()
q1.enqueue("The first element")
print(q1.first.value)
print(q1.last.value)
print(q1)
q2 = Queue("The first element")
print(q1 == q2)
print("      *** dequeue *** ")
q1 = Queue(1, 2, 3, 4)
print(q1.dequeue().value)
q2 = Queue(2, 3, 4)
print(q1 == q2)
print(q1)
print("      *** dequeue the last element *** ")
q1 = Queue("The last element")
q1.dequeue()
print(q1.first)
print(q1.last)
print(q1)
q2 = Queue()
print(q1 == q2)
